# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'de-wiring/debian-7.8'
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end
  config.vm.synced_folder "tests/", "/tests"

  config.vm.provision 'shell', path: 'provision.d/01_os.sh'
  config.vm.provision 'shell', path: 'provision.d/05_ruby.sh'
  config.vm.provision 'shell', path: 'provision.d/20_serverspec.sh'
  config.vm.provision 'shell', path: 'provision.d/21_run_serverspec.sh'

end
